"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-08 13:35:58.031461
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_prompt_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_template", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_prompt_versions")),
        sa.UniqueConstraint("key", "version", name=op.f("uq_ai_prompt_versions_key")),
    )
    op.create_index(op.f("ix_ai_prompt_versions_key"), "ai_prompt_versions", ["key"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("full", name="assessment_kind", native_enum=False, create_constraint=True, length=32),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
        sa.UniqueConstraint("code", name=op.f("uq_assessments_code")),
    )
    op.create_table(
        "competency_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color_token", sa.String(length=48), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competency_areas")),
        sa.UniqueConstraint("code", name=op.f("uq_competency_areas_code")),
    )
    op.create_table(
        "competency_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("min_score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competency_levels")),
        sa.UniqueConstraint("name", name=op.f("uq_competency_levels_name")),
        sa.UniqueConstraint("rank", name=op.f("uq_competency_levels_rank")),
    )
    op.create_table(
        "goal_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goal_definitions")),
        sa.UniqueConstraint("code", name=op.f("uq_goal_definitions_code")),
    )
    op.create_table(
        "revoked_tokens",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("jti", name=op.f("pk_revoked_tokens")),
    )
    op.create_index(op.f("ix_revoked_tokens_expires_at"), "revoked_tokens", ["expires_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="user_role", native_enum=False, create_constraint=True, length=32),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "competencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_name", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("reflection_prompt", sa.Text(), nullable=True),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("learning_priority", sa.Float(), nullable=False),
        sa.Column("default_target", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["competency_areas.id"],
            name=op.f("fk_competencies_area_id_competency_areas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competencies")),
    )
    op.create_index(op.f("ix_competencies_area_id"), "competencies", ["area_id"], unique=False)
    op.create_index(op.f("ix_competencies_code"), "competencies", ["code"], unique=True)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "likert",
                "situational",
                "open",
                "practical",
                name="question_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("rubric", sa.JSON(), nullable=True),
        sa.Column("reverse_scored", sa.Boolean(), nullable=False),
        sa.Column("min_length", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_questions_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    op.create_index(op.f("ix_questions_assessment_id"), "questions", ["assessment_id"], unique=False)
    op.create_table(
        "user_goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goal_definitions.id"],
            name=op.f("fk_user_goals_goal_id_goal_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_goals")),
        sa.UniqueConstraint("user_id", "goal_id", name=op.f("uq_user_goals_user_id")),
    )
    op.create_index(op.f("ix_user_goals_user_id"), "user_goals", ["user_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("education", sa.String(length=120), nullable=True),
        sa.Column("background", sa.Text(), nullable=True),
        sa.Column(
            "entrepreneurial_experience",
            sa.Enum(
                "none",
                "side_project",
                "startup_team",
                "running_business",
                name="experience_level",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("business_experience", sa.Text(), nullable=True),
        sa.Column(
            "preferred_learning_format",
            sa.Enum(
                "article",
                "video",
                "course",
                "mixed",
                name="learning_format",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("weekly_learning_minutes", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("notify_reassessment", sa.Boolean(), nullable=False),
        sa.Column("notify_weekly_summary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_profiles_user_id")),
    )
    op.create_table(
        "assessment_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("assessment_id", sa.Integer(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("full", "competency", name="attempt_scope", native_enum=False, create_constraint=True, length=32),
            nullable=False,
        ),
        sa.Column("scope_competency_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "completed",
                "abandoned",
                name="attempt_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("current_index", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_assessment_attempts_assessment_id_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_competency_id"],
            ["competencies.id"],
            name=op.f("fk_assessment_attempts_scope_competency_id_competencies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assessment_attempts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_attempts")),
    )
    op.create_index(
        op.f("ix_assessment_attempts_assessment_id"), "assessment_attempts", ["assessment_id"], unique=False
    )
    op.create_index(op.f("ix_assessment_attempts_status"), "assessment_attempts", ["status"], unique=False)
    op.create_index(op.f("ix_assessment_attempts_user_id"), "assessment_attempts", ["user_id"], unique=False)
    op.create_table(
        "goal_competency_weights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_goal_competency_weights_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goal_definitions.id"],
            name=op.f("fk_goal_competency_weights_goal_id_goal_definitions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goal_competency_weights")),
        sa.UniqueConstraint("goal_id", "competency_id", name=op.f("uq_goal_competency_weights_goal_id")),
    )
    op.create_index(
        op.f("ix_goal_competency_weights_competency_id"), "goal_competency_weights", ["competency_id"], unique=False
    )
    op.create_index(op.f("ix_goal_competency_weights_goal_id"), "goal_competency_weights", ["goal_id"], unique=False)
    op.create_table(
        "learning_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "article",
                "video",
                "course",
                "exercise",
                "case_study",
                "template",
                name="resource_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                name="difficulty",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_learning_resources_competency_id_competencies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_resources")),
        sa.UniqueConstraint("slug", name=op.f("uq_learning_resources_slug")),
    )
    op.create_index(op.f("ix_learning_resources_competency_id"), "learning_resources", ["competency_id"], unique=False)
    op.create_table(
        "practical_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                name="difficulty",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("rubric", sa.JSON(), nullable=False),
        sa.Column("min_length", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_practical_tasks_competency_id_competencies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practical_tasks")),
        sa.UniqueConstraint("slug", name=op.f("uq_practical_tasks_slug")),
    )
    op.create_index(op.f("ix_practical_tasks_competency_id"), "practical_tasks", ["competency_id"], unique=False)
    op.create_table(
        "question_competencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.CheckConstraint("weight > 0 AND weight <= 1", name=op.f("ck_question_competencies_weight_range")),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_question_competencies_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_competencies_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_competencies")),
        sa.UniqueConstraint("question_id", "competency_id", name=op.f("uq_question_competencies_question_id")),
    )
    op.create_index(
        op.f("ix_question_competencies_competency_id"), "question_competencies", ["competency_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_competencies_question_id"), "question_competencies", ["question_id"], unique=False
    )
    op.create_table(
        "question_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.CheckConstraint("score >= 0 AND score <= 100", name=op.f("ck_question_options_score_range")),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_options_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_options")),
    )
    op.create_index(op.f("ix_question_options_question_id"), "question_options", ["question_id"], unique=False)
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=True),
        sa.Column("text_response", sa.Text(), nullable=True),
        sa.Column("item_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_answers_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["question_options.id"],
            name=op.f("fk_answers_option_id_question_options"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_answers_question_id_questions"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
        sa.UniqueConstraint("attempt_id", "question_id", name=op.f("uq_answers_attempt_id")),
    )
    op.create_index(op.f("ix_answers_attempt_id"), "answers", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_answers_question_id"), "answers", ["question_id"], unique=False)
    op.create_table(
        "competency_gaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("current_score", sa.Integer(), nullable=False),
        sa.Column("target_score", sa.Integer(), nullable=False),
        sa.Column("gap", sa.Integer(), nullable=False),
        sa.Column(
            "band",
            sa.Enum("high", "medium", "low", name="gap_band", native_enum=False, create_constraint=True, length=32),
            nullable=False,
        ),
        sa.Column("goal_relevance", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("learning_priority", sa.Float(), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("priority_rank", sa.Integer(), nullable=False),
        sa.Column("priority_label", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_competency_gaps_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_competency_gaps_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_competency_gaps_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competency_gaps")),
        sa.UniqueConstraint("attempt_id", "competency_id", name=op.f("uq_competency_gaps_attempt_id")),
    )
    op.create_index(op.f("ix_competency_gaps_attempt_id"), "competency_gaps", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_competency_gaps_competency_id"), "competency_gaps", ["competency_id"], unique=False)
    op.create_index(op.f("ix_competency_gaps_user_id"), "competency_gaps", ["user_id"], unique=False)
    op.create_table(
        "competency_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("raw_score", sa.Float(), nullable=False),
        sa.Column("max_raw_score", sa.Float(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("self_score", sa.Float(), nullable=True),
        sa.Column("situational_score", sa.Float(), nullable=True),
        sa.Column("open_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= 100", name=op.f("ck_competency_scores_score_range")),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_competency_scores_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_competency_scores_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["competency_levels.id"],
            name=op.f("fk_competency_scores_level_id_competency_levels"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_competency_scores_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competency_scores")),
        sa.UniqueConstraint("attempt_id", "competency_id", name=op.f("uq_competency_scores_attempt_id")),
    )
    op.create_index(op.f("ix_competency_scores_attempt_id"), "competency_scores", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_competency_scores_competency_id"), "competency_scores", ["competency_id"], unique=False)
    op.create_index(op.f("ix_competency_scores_created_at"), "competency_scores", ["created_at"], unique=False)
    op.create_index(op.f("ix_competency_scores_user_id"), "competency_scores", ["user_id"], unique=False)
    op.create_table(
        "practice_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "started",
                "submitted",
                "completed",
                name="practice_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("feedback_score", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["practical_tasks.id"],
            name=op.f("fk_practice_submissions_task_id_practical_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_practice_submissions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_submissions")),
        sa.UniqueConstraint("user_id", "task_id", name=op.f("uq_practice_submissions_user_id")),
    )
    op.create_index(op.f("ix_practice_submissions_task_id"), "practice_submissions", ["task_id"], unique=False)
    op.create_index(op.f("ix_practice_submissions_user_id"), "practice_submissions", ["user_id"], unique=False)
    op.create_table(
        "progress_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("ideas_score", sa.Integer(), nullable=False),
        sa.Column("resources_score", sa.Integer(), nullable=False),
        sa.Column("action_score", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("completed_resources", sa.Integer(), nullable=False),
        sa.Column("completed_tasks", sa.Integer(), nullable=False),
        sa.Column("plan_progress_pct", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_progress_snapshots_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_progress_snapshots_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_snapshots")),
        sa.UniqueConstraint("attempt_id", name=op.f("uq_progress_snapshots_attempt_id")),
    )
    op.create_index(op.f("ix_progress_snapshots_created_at"), "progress_snapshots", ["created_at"], unique=False)
    op.create_index(op.f("ix_progress_snapshots_user_id"), "progress_snapshots", ["user_id"], unique=False)
    op.create_table(
        "reassessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("previous_attempt_id", sa.Integer(), nullable=True),
        sa.Column("competency_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_reassessments_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_reassessments_competency_id_competencies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_reassessments_previous_attempt_id_assessment_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reassessments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reassessments")),
        sa.UniqueConstraint("attempt_id", name=op.f("uq_reassessments_attempt_id")),
    )
    op.create_index(op.f("ix_reassessments_user_id"), "reassessments", ["user_id"], unique=False)
    op.create_table(
        "user_learning_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "in_progress",
                "completed",
                name="progress_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "progress_pct >= 0 AND progress_pct <= 100", name=op.f("ck_user_learning_progress_pct_range")
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_user_learning_progress_resource_id_learning_resources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_learning_progress_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_learning_progress")),
        sa.UniqueConstraint("user_id", "resource_id", name=op.f("uq_user_learning_progress_user_id")),
    )
    op.create_index(
        op.f("ix_user_learning_progress_resource_id"), "user_learning_progress", ["resource_id"], unique=False
    )
    op.create_index(op.f("ix_user_learning_progress_user_id"), "user_learning_progress", ["user_id"], unique=False)
    op.create_table(
        "ai_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("attempt_id", sa.Integer(), nullable=True),
        sa.Column("answer_id", sa.Integer(), nullable=True),
        sa.Column("practice_submission_id", sa.Integer(), nullable=True),
        sa.Column("competency_id", sa.Integer(), nullable=True),
        sa.Column("prompt_version_id", sa.Integer(), nullable=True),
        sa.Column(
            "input_type",
            sa.Enum(
                "open_answer",
                "practical_answer",
                "practice_submission",
                "profile_insight",
                name="ai_input_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "retried",
                "fallback",
                name="ai_eval_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("input_excerpt", sa.Text(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("strengths", sa.JSON(), nullable=True),
        sa.Column("development_areas", sa.JSON(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answers.id"], name=op.f("fk_ai_evaluations_answer_id_answers"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_ai_evaluations_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_ai_evaluations_competency_id_competencies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["practice_submission_id"],
            ["practice_submissions.id"],
            name=op.f("fk_ai_evaluations_practice_submission_id_practice_submissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["ai_prompt_versions.id"],
            name=op.f("fk_ai_evaluations_prompt_version_id_ai_prompt_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_evaluations_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_evaluations")),
    )
    op.create_index(op.f("ix_ai_evaluations_answer_id"), "ai_evaluations", ["answer_id"], unique=False)
    op.create_index(op.f("ix_ai_evaluations_attempt_id"), "ai_evaluations", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_ai_evaluations_created_at"), "ai_evaluations", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_ai_evaluations_practice_submission_id"), "ai_evaluations", ["practice_submission_id"], unique=False
    )
    op.create_index(op.f("ix_ai_evaluations_user_id"), "ai_evaluations", ["user_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("gap_id", sa.Integer(), nullable=False),
        sa.Column("competency_id", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("priority_score", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "completed",
                "superseded",
                name="recommendation_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["assessment_attempts.id"],
            name=op.f("fk_recommendations_attempt_id_assessment_attempts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
            name=op.f("fk_recommendations_competency_id_competencies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gap_id"],
            ["competency_gaps.id"],
            name=op.f("fk_recommendations_gap_id_competency_gaps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goal_definitions.id"],
            name=op.f("fk_recommendations_goal_id_goal_definitions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_recommendations_resource_id_learning_resources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["practical_tasks.id"],
            name=op.f("fk_recommendations_task_id_practical_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_recommendations_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(op.f("ix_recommendations_attempt_id"), "recommendations", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_recommendations_competency_id"), "recommendations", ["competency_id"], unique=False)
    op.create_index(op.f("ix_recommendations_status"), "recommendations", ["status"], unique=False)
    op.create_index(op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False)
    op.create_table(
        "learning_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "learn",
                "practice",
                "reflect",
                "reassess",
                name="activity_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "in_progress",
                "done",
                name="activity_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_learning_activities_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["learning_resources.id"],
            name=op.f("fk_learning_activities_resource_id_learning_resources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["practical_tasks.id"],
            name=op.f("fk_learning_activities_task_id_practical_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_learning_activities_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_activities")),
        sa.UniqueConstraint("recommendation_id", "kind", name=op.f("uq_learning_activities_recommendation_id")),
    )
    op.create_index(
        op.f("ix_learning_activities_recommendation_id"), "learning_activities", ["recommendation_id"], unique=False
    )
    op.create_index(op.f("ix_learning_activities_user_id"), "learning_activities", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learning_activities_user_id"), table_name="learning_activities")
    op.drop_index(op.f("ix_learning_activities_recommendation_id"), table_name="learning_activities")
    op.drop_table("learning_activities")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_status"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_competency_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_attempt_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_ai_evaluations_user_id"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_practice_submission_id"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_created_at"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_attempt_id"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_answer_id"), table_name="ai_evaluations")
    op.drop_table("ai_evaluations")
    op.drop_index(op.f("ix_user_learning_progress_user_id"), table_name="user_learning_progress")
    op.drop_index(op.f("ix_user_learning_progress_resource_id"), table_name="user_learning_progress")
    op.drop_table("user_learning_progress")
    op.drop_index(op.f("ix_reassessments_user_id"), table_name="reassessments")
    op.drop_table("reassessments")
    op.drop_index(op.f("ix_progress_snapshots_user_id"), table_name="progress_snapshots")
    op.drop_index(op.f("ix_progress_snapshots_created_at"), table_name="progress_snapshots")
    op.drop_table("progress_snapshots")
    op.drop_index(op.f("ix_practice_submissions_user_id"), table_name="practice_submissions")
    op.drop_index(op.f("ix_practice_submissions_task_id"), table_name="practice_submissions")
    op.drop_table("practice_submissions")
    op.drop_index(op.f("ix_competency_scores_user_id"), table_name="competency_scores")
    op.drop_index(op.f("ix_competency_scores_created_at"), table_name="competency_scores")
    op.drop_index(op.f("ix_competency_scores_competency_id"), table_name="competency_scores")
    op.drop_index(op.f("ix_competency_scores_attempt_id"), table_name="competency_scores")
    op.drop_table("competency_scores")
    op.drop_index(op.f("ix_competency_gaps_user_id"), table_name="competency_gaps")
    op.drop_index(op.f("ix_competency_gaps_competency_id"), table_name="competency_gaps")
    op.drop_index(op.f("ix_competency_gaps_attempt_id"), table_name="competency_gaps")
    op.drop_table("competency_gaps")
    op.drop_index(op.f("ix_answers_question_id"), table_name="answers")
    op.drop_index(op.f("ix_answers_attempt_id"), table_name="answers")
    op.drop_table("answers")
    op.drop_index(op.f("ix_question_options_question_id"), table_name="question_options")
    op.drop_table("question_options")
    op.drop_index(op.f("ix_question_competencies_question_id"), table_name="question_competencies")
    op.drop_index(op.f("ix_question_competencies_competency_id"), table_name="question_competencies")
    op.drop_table("question_competencies")
    op.drop_index(op.f("ix_practical_tasks_competency_id"), table_name="practical_tasks")
    op.drop_table("practical_tasks")
    op.drop_index(op.f("ix_learning_resources_competency_id"), table_name="learning_resources")
    op.drop_table("learning_resources")
    op.drop_index(op.f("ix_goal_competency_weights_goal_id"), table_name="goal_competency_weights")
    op.drop_index(op.f("ix_goal_competency_weights_competency_id"), table_name="goal_competency_weights")
    op.drop_table("goal_competency_weights")
    op.drop_index(op.f("ix_assessment_attempts_user_id"), table_name="assessment_attempts")
    op.drop_index(op.f("ix_assessment_attempts_status"), table_name="assessment_attempts")
    op.drop_index(op.f("ix_assessment_attempts_assessment_id"), table_name="assessment_attempts")
    op.drop_table("assessment_attempts")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_goals_user_id"), table_name="user_goals")
    op.drop_table("user_goals")
    op.drop_index(op.f("ix_questions_assessment_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_competencies_code"), table_name="competencies")
    op.drop_index(op.f("ix_competencies_area_id"), table_name="competencies")
    op.drop_table("competencies")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_revoked_tokens_expires_at"), table_name="revoked_tokens")
    op.drop_table("revoked_tokens")
    op.drop_table("goal_definitions")
    op.drop_table("competency_levels")
    op.drop_table("competency_areas")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_ai_prompt_versions_key"), table_name="ai_prompt_versions")
    op.drop_table("ai_prompt_versions")
    # ### end Alembic commands ###
