"""EntreComp (European Entrepreneurship Competence Framework): 3 areas, 15 competencies."""

AREAS = [
    ("ideas", "Ideas & Opportunities", "--domain-ideas"),
    ("resources", "Resources", "--domain-resources"),
    ("action", "Into Action", "--domain-action"),
]

# code, area, name, short, importance, learning_priority, description, hint, reflection prompt
COMPETENCIES = [
    (
        "spotting",
        "ideas",
        "Spotting Opportunities",
        "Opportunities",
        0.9,
        0.8,
        "Using your imagination and abilities to identify opportunities for creating value: noticing unmet needs, "
        "challenges and trends in your environment.",
        "You notice unmet needs in everyday situations and turn them into opportunities.",
        "Which problem around you did you notice this week, and who exactly has it?",
    ),
    (
        "creativity",
        "ideas",
        "Creativity",
        "Creativity",
        0.7,
        0.6,
        "Developing several ideas and opportunities to create value, exploring and experimenting with innovative "
        "approaches and combining knowledge and resources.",
        "Your ability to generate and combine new ideas.",
        "Which of your ideas this week came from combining two things that do not usually go together?",
    ),
    (
        "vision",
        "ideas",
        "Vision",
        "Vision",
        0.7,
        0.5,
        "Imagining the future and developing a vision that turns ideas into action; visualising future scenarios to "
        "guide effort.",
        "You can describe where an idea could go in three to five years.",
        "Describe in three sentences what your idea looks like in five years. What has to be true for it to happen?",
    ),
    (
        "valuing",
        "ideas",
        "Valuing Ideas",
        "Valuing",
        0.8,
        0.6,
        "Judging what value is in social, cultural and economic terms; recognising the potential an idea has and "
        "finding ways to make the most of it, including protecting it.",
        "You can judge which ideas are worth pursuing and why.",
        "Which assumption about your idea's value are you least sure about, and how could you test it cheaply?",
    ),
    (
        "ethics",
        "ideas",
        "Ethical & Sustainable Thinking",
        "Ethics",
        0.6,
        0.4,
        "Assessing the consequences and impact of ideas, opportunities and actions on people, communities and the "
        "environment; acting responsibly.",
        "You weigh the impact of your choices on people and the environment.",
        "Who could be negatively affected by your idea, and what would you change to reduce that impact?",
    ),
    (
        "self-awareness",
        "resources",
        "Self-awareness & Self-efficacy",
        "Self-aware.",
        0.6,
        0.7,
        "Reflecting on your needs, aspirations and wants; identifying and assessing your strengths and weaknesses; "
        "believing in your ability to influence events.",
        "You know your strengths and believe you can make things happen.",
        "Which strength helped you most this week, and which weakness slowed you down?",
    ),
    (
        "motivation",
        "resources",
        "Motivation & Perseverance",
        "Motivation",
        0.7,
        0.6,
        "Staying focused and not giving up; being determined to turn ideas into action, being patient and resilient "
        "under pressure and after failure.",
        "You stay committed when things get difficult.",
        "When did you feel like giving up recently, and what kept you going?",
    ),
    (
        "mobilizing-resources",
        "resources",
        "Mobilizing Resources",
        "Resources",
        0.8,
        0.6,
        "Getting and managing the material, non-material and digital resources needed to turn ideas into action; "
        "making the most of limited resources.",
        "You find and use the people, tools and materials an idea needs.",
        "Which resource outside your own network could you ask for this week, and from whom?",
    ),
    (
        "financial-literacy",
        "resources",
        "Financial & Economic Literacy",
        "Finance",
        0.9,
        0.9,
        "Estimating the cost of turning an idea into a value-creating activity; planning, putting in place and "
        "evaluating financial decisions over time; managing financing.",
        "Estimating costs, pricing and cash flow for an idea.",
        "What financial assumption creates the biggest risk for your business idea?",
    ),
    (
        "mobilizing-others",
        "resources",
        "Mobilizing Others",
        "Mobilizing",
        0.8,
        0.6,
        "Inspiring and enthusing relevant stakeholders; getting the support needed to achieve valuable outcomes; "
        "communicating persuasively.",
        "You get others to support and join your ideas.",
        "Whose support do you need next, and what is in it for them?",
    ),
    (
        "initiative",
        "action",
        "Taking the Initiative",
        "Initiative",
        0.8,
        0.7,
        "Initiating processes that create value; taking up challenges; acting and working independently to achieve "
        "goals, sticking to intentions and carrying out planned tasks.",
        "You start things without waiting to be asked.",
        "What did you start this week that nobody asked you to do?",
    ),
    (
        "planning",
        "action",
        "Planning & Management",
        "Planning",
        0.8,
        0.8,
        "Setting long-, medium- and short-term goals; defining priorities and action plans; adapting to unforeseen "
        "changes.",
        "You turn goals into milestones, owners and deadlines.",
        "Which milestone in your plan depends on someone else, and how will you follow up?",
    ),
    (
        "uncertainty",
        "action",
        "Coping with Uncertainty, Ambiguity & Risk",
        "Uncertainty",
        0.8,
        0.7,
        "Making decisions when the result is uncertain, information is partial or ambiguous, or there is a risk of "
        "unintended outcomes; testing ideas early to reduce risk of failing.",
        "You decide and act even when information is incomplete.",
        "Describe a recent decision you postponed. What information were you waiting for?",
    ),
    (
        "teamwork",
        "action",
        "Working with Others",
        "Teamwork",
        0.7,
        0.5,
        "Working together and cooperating with others to develop ideas and turn them into action; networking; "
        "solving conflicts and facing up to competition positively.",
        "You collaborate well and adapt your role to the team.",
        "What did you do this week that made your team work better together?",
    ),
    (
        "learning-experience",
        "action",
        "Learning Through Experience",
        "Learning",
        0.7,
        0.8,
        "Reflecting and learning from both success and failure (your own and other people's); learning with others "
        "and from experience.",
        "You reflect on results and change what you do next time.",
        "What is one thing that did not go as planned, and what will you do differently?",
    ),
]

GOALS = [
    (
        "launch-startup",
        "Launch my own startup",
        "Turn an idea into a working venture.",
        {
            "spotting": 0.9,
            "valuing": 0.8,
            "financial-literacy": 0.9,
            "mobilizing-resources": 0.8,
            "planning": 0.8,
            "uncertainty": 0.8,
            "initiative": 0.8,
            "mobilizing-others": 0.7,
            "vision": 0.7,
            "creativity": 0.6,
            "motivation": 0.7,
            "teamwork": 0.6,
            "learning-experience": 0.6,
            "self-awareness": 0.5,
            "ethics": 0.5,
        },
    ),
    (
        "join-team",
        "Join a startup team",
        "Contribute to an early-stage team.",
        {
            "teamwork": 0.9,
            "initiative": 0.7,
            "learning-experience": 0.7,
            "motivation": 0.7,
            "creativity": 0.6,
            "uncertainty": 0.6,
            "planning": 0.6,
            "self-awareness": 0.6,
        },
    ),
    (
        "university-project",
        "Develop a project at my university",
        "Lead or join a student or research project.",
        {
            "planning": 0.8,
            "teamwork": 0.8,
            "mobilizing-others": 0.7,
            "creativity": 0.7,
            "vision": 0.6,
            "initiative": 0.7,
        },
    ),
    (
        "grow-business",
        "Grow an existing business",
        "Improve a business you already run or work in.",
        {
            "financial-literacy": 0.9,
            "planning": 0.8,
            "mobilizing-resources": 0.8,
            "valuing": 0.7,
            "mobilizing-others": 0.7,
            "spotting": 0.7,
            "ethics": 0.6,
            "uncertainty": 0.7,
        },
    ),
    (
        "social-impact",
        "Create social or environmental impact",
        "Build something that improves a community.",
        {"ethics": 0.9, "vision": 0.8, "valuing": 0.7, "mobilizing-others": 0.8, "spotting": 0.7, "motivation": 0.7},
    ),
    (
        "career-skills",
        "Build entrepreneurial skills for my career",
        "Become more proactive and adaptable at work.",
        {
            "self-awareness": 0.8,
            "learning-experience": 0.8,
            "initiative": 0.8,
            "motivation": 0.7,
            "teamwork": 0.7,
            "creativity": 0.6,
        },
    ),
]
